import Head from "next/head"

import React from 'react'
import {client} from '../lib/client';
import { urlFor } from '../lib/client';

const HomePage = ({IntroData}) => {
  return (
    <div className="body">
      <Head>
        <title>Team 4 </title>
        <meta name="description" content="Generated by Create Vlaunch app"/>
        <link rel="icon" href="/pro.ico"/>
      </Head>
      <div className="Home-Container">
        <img src={urlFor(IntroData[0].image && IntroData[0].image)} alt=""/>
        <h1>{IntroData[0].title}</h1>
        {/* <h4>{IntroData[0].subtitle}</h4> */}
      </div>
    </div>
  )
}

export const getServerSideProps = async () => {
  const IntroQuery = `*[_type == "home"]`;
  const IntroData = await client.fetch(IntroQuery);
  
  return {
    props: {
      IntroData
    }
  }
}

export default HomePage
